name: BraintreePaymentGraphQL
jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: macOS
    vmImage: macOS-latest

- template: azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-latest

- template: azure-pipelines-template.yml
  parameters:
    name: Windows
    vmImage: windows-latest