[package]
name = "braintreepayment_graphql"
version = "0.1.0"
authors = ["David Gräff <david.graeff@web.de>"]
edition = "2018"
license = "MIT"
description = "This crate allows easy access to the [Braintree](https://www.braintreepayments.com) API via the GraphQL interface."
#cargo-features = ["default-run"]
#default-run = "braintree-queries"

[dependencies]
url  = "2.1.0"
reqwest = "0.9.20"
chrono = { version = "0.4.7", features = ["serde"] }
#graphql_client = "0.8.0"
#graphql_client_codegen = "0.8.0"

graphql_client_codegen = { git = "https://github.com/davidgraeff/graphql-client", branch = "master" }
graphql_client = { git = "https://github.com/davidgraeff/graphql-client", branch = "master" }
failure = "0.1.5"
syn = { version = "^1.0", features = ["extra-traits"] }

rustfmt-nightly = { version = "1.4.5", optional = true }
serde_json = "^1.0"
serde = "^1.0"
rust_decimal = "1.0.3"
rust_decimal_macros = "1.0.3"
quote = "1.0.2"
tempfile = "3.1.0"
rand = "0.7.0"
doc-comment = "0.3.1"

[dev-dependencies]
cargo-husky = "1.2.0"
galvanic-test = "0.2.0"

[features]
default = ["rustfmt"]
rustfmt = ["rustfmt-nightly"]
