name: StaticLibMusl

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: davidgraeff/rust-musl-action@master
    - uses: actions/checkout@master
    - name: Check for leftover println
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
      run: ./ci.sh
    - name: Build and Test
      run: cargo test --features rustls-tls --no-default-features
