name: Code Style

on:
  pull_request:
  push:
    paths:
      - 'src/*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check for leftover println
        run: ./tests/left_over_println.sh
      - name: Check formatting
        run: cargo fmt --all -- --check
